In [1]:
import numpy as np
np.array([1,2,3])

array([1, 2, 3])

In [3]:
a=np.array([1,2,3])

In [4]:
dizi=np.array([1,2,3,3.14])
dizi

array([1.  , 2.  , 3.  , 3.14])

In [5]:
dizi=np.array([1,2,3,3.14],dtype=int)
dizi

array([1, 2, 3, 3])

In [6]:
birboyut=np.array([1,2,3])
birboyut

array([1, 2, 3])

In [7]:
ikiboyut = np.array([[1,2,3], [4,5,6]])
ikiboyut

array([[1, 2, 3],
       [4, 5, 6]])