In [104]:
import numpy as np #numpy kütüphanesini np takma adı
dizi=np.full((4,3),5)
dizi

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [3]:
#yeni bir numpy dizisi oluştur
np.array([1,2,3])

array([1, 2, 3])

In [5]:
#oluşturduğunuz diziyi bir değişkene aktarıyoruz
dizi=np.array(["elma","erik","iğde"])
dizi

array(['elma', 'erik', 'iğde'], dtype='<U4')

In [13]:
dizi

array([1.  , 2.  , 3.14])

In [23]:
dizi=np.array([1,2,3])
dizi=np.array([1,2,3.14])
dizi.dtype

dtype('float64')

In [43]:
dizi=np.array([1,2,3.14],dtype=int)

In [68]:
birboyut=np.array([1,2,3,4])
ikiboyut=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
ikiboyut #ne yazarsan onu çaliştırır.

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [70]:
np.zeros(7)

array([0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((2,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0]])

In [74]:
np.ones(3)

array([1., 1., 1.])

In [76]:
np.full((4,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [78]:
np.arange(2,22,5)

array([ 2,  7, 12, 17])

In [80]:
np.linspace(2,10,num=7)

array([ 2.        ,  3.33333333,  4.66666667,  6.        ,  7.33333333,
        8.66666667, 10.        ])

In [98]:
np.random.randint(0,10,5)

array([2, 6, 5, 0, 9])

In [100]:
np.random.randint(0,10,(5,2))

array([[2, 5],
       [7, 4],
       [1, 7],
       [1, 0],
       [3, 3]])

In [114]:
dizi=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
dizi.shape

(3, 4)

In [116]:
dizi.ndim

2

In [118]:
dizi.size

12

In [120]:
dizi.itemsize

4